---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test
  namespace: ${KUBE_NAMESPACE}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-test
  template:
    metadata:
      labels:
        app: devops-test
    spec:
      containers:
        - name: devops-test
          image: ${IMAGE}:${CONTAINER_VERSION}
          ports:
            - containerPort: 3000
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: devops-test
  namespace: ${KUBE_NAMESPACE}
spec:
  selector:
    app: devops-test
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: devops-test-ingress
  namespace: ${KUBE_NAMESPACE}
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: devops-test
              servicePort: 80
